// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Persistence.DataBaseContext;

#nullable disable

namespace StudentManagement.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    partial class MenuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Persistence.Model.IngredientCombo", b =>
                {
                    b.Property<int>("IngredientComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IngredientComboId"));

                    b.Property<int>("Ingredient1")
                        .HasColumnType("int");

                    b.Property<int>("Ingredient2")
                        .HasColumnType("int");

                    b.Property<int>("Ingredient3")
                        .HasColumnType("int");

                    b.HasKey("IngredientComboId");

                    b.ToTable("IngredientCombos");
                });

            modelBuilder.Entity("StudentManagement.Persistence.Model.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("MenuTypeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientComboId")
                        .HasColumnType("int");

                    b.HasKey("MenuId", "MenuTypeId");

                    b.HasIndex("IngredientComboId");

                    b.HasIndex("MenuTypeId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("StudentManagement.Persistence.Model.MenuName", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("MenuNameValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MenuId");

                    b.ToTable("MenuNames");
                });

            modelBuilder.Entity("StudentManagement.Persistence.Model.MenuType", b =>
                {
                    b.Property<int>("MenuTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MenuTypeId"));

                    b.Property<string>("MenuTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MenuTypeId");

                    b.ToTable("MenuTypes");
                });

            modelBuilder.Entity("StudentManagement.Persistence.Model.Menu", b =>
                {
                    b.HasOne("StudentManagement.Persistence.Model.IngredientCombo", "IngredientCombo")
                        .WithMany("Menus")
                        .HasForeignKey("IngredientComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Persistence.Model.MenuName", "MenuName")
                        .WithMany("Menus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Persistence.Model.MenuType", "MenuType")
                        .WithMany("Menus")
                        .HasForeignKey("MenuTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientCombo");

                    b.Navigation("MenuName");

                    b.Navigation("MenuType");
                });

            modelBuilder.Entity("StudentManagement.Persistence.Model.IngredientCombo", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("StudentManagement.Persistence.Model.MenuName", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("StudentManagement.Persistence.Model.MenuType", b =>
                {
                    b.Navigation("Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
